{{- $httpRoute := .Values.httpRoute | default dict -}}
{{- if and ($httpRoute.enabled | default false) ($httpRoute.createReferenceGrant | default false) -}}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: {{ $httpRoute.refGrantName }}
  namespace: envoy-gateway-system
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: {{ $httpRoute.namespace }}
  to:
  - group: gateway.networking.k8s.io
    kind: Gateway
{{- end }}
